### ISSUE TITLE
Auto-Reload einrichten?

### ISSUE THREAD

**Issue by Xendiadyon** [ContaoBlackForest/contao-encore-bundle#1]
Moin @baumannsven ,

wir hatten ja mal darüber geredet, dass ich bei meinem privaten Relaunch (Contao 4.9) encore verwende. Jetzt ist es so weit

Ich habe nach ziemlichem Hin-und-Her auf meinem Shared-Hoster endlich encore mit deiner Erweiterung zum Laufen bekommen, allerdings funktioniert das auto-reload der Browserfenster bei aktualisiertem Code noch nicht.
Leider gibt es hier bei deiner Erweiterung noch keine Dokumentation und ich bin etwas am Schwimmen.

Ich dachte, dass autoreload automatisch aktiviert ist, sobald man sich im Debug-Modus befindet? Hast du vielleicht eine kurze Anleitung?

Vielen Dank!

**Comment by baumannsven** [comment]
Das was du meinst ist das Hot Replacement Module von Webpack das du konfigurieren musst. Hat selbst mit diesem Bundle nichts zu tun.
